on:
  schedule:
    - cron: '0 9 5 */2 *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'ğŸ™ Tag & Push'
        shell: bash
        run: |
          git config --local user.name "mio"
          git config --local user.email "mio@lazym.io"
          git tag "v`date +'%Y.%m.%d'`"
  
      - name: 'ğŸ™ Push tags to trigger building'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          branch: ${{ github.ref }}
          tags: true